name: 'Remind to update the WDYD summary'

on:
  schedule:
    - cron: '0 12 * * FRI'
  workflow_dispatch:

jobs:
  publish:
    name: 'Send the reminder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Set the dynamic reminder message'
        run: echo "REMINDER_MESSAGE=${{ vars.ZULIP_PING }} don't forget to update your latest work items in [${{ vars.PROJECT_TITLE }}](https://github.com/${GITHUB_REPOSITORY}) -- the summary will be published on Monday, 10 minutes before the company call." >> $GITHUB_ENV
      - name: 'Send the message to Zulip'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ vars.ZULIP_BOT_EMAIL }}
          organization-url: ${{ vars.ZULIP_ORGANIZATION_URL }}
          to: ${{ vars.ZULIP_STREAM }}
          type: 'stream'
          topic: ${{ vars.ZULIP_TOPIC }}
          content: ${{ env.REMINDER_MESSAGE }}
